[book]
authors = ["longshuai"]
language = "en"
multilingual = false
src = "src"
title = "Systemd系列文章"
description = "systemd系列文章"

[output.html]
theme = "mytheme"
default-theme = "rust"
copy-fonts = false
additional-css = ["mytheme/fonts/cascadia-font.css","mytheme/style.css"]
additional-js = ["mytheme/sidebar.js"]

[output.html.font]
enable = true
woff = true