- name: install nodejs npm
  apt: 
    name: nodejs,npm
    state: present 

- name: install hexo-cli
  npm: 
    name: hexo-cli
    global: yes

- name: copy hexo.service to /usr/lib/systemd/system
  template: 
    src: hexo/hexo.service.j2
    dest: /usr/lib/systemd/system/hexo.service

- shell: 'systemctl daemon-reload'

- name: enable trojan@.service
  service: 
    name: hexo
    enabled: yes

- name: install npms in /blog
  npm:
    path: /blog
  failed_when: false

- name: start hexo
  service: 
    name: hexo
    state: started
