- name: install rust
  shell: |
    curl https://sh.rustup.rs -sSf | sh
    cargo install mdbook

- name: copy mdbook.service to /usr/lib/systemd/system
  template: 
    src: mdbook/mdbook_{{item}}.service.j2
    dest: /usr/lib/systemd/system/mdbook_{{item}}.service
  loop: 
    - rust
    - perl
    - systemd

- shell: 'systemctl daemon-reload'

- name: enable mdbook.service
  service: 
    name: mdbook_{{item}}
    enabled: yes
  loop: 
    - rust
    - perl
    - systemd

- name: copy book.conf to /etc/nginx/conf.d/book.conf 
  template: 
    src: nginx/book.conf.j2
    dest: /etc/nginx/conf.d/book.conf