- name: install nginx
  apt: 
    name: nginx
    state: present 

- name: create nginx ssl path
  file: 
    name: "{{nginx_ssl_path}}"
    state: directory
    mode: 0755

- name: copy ssl files
  template:
    src: 'ssl/{{item}}.j2'
    dest: '{{nginx_ssl_path}}/{{item}}'
  loop:
    - '{{blog_domain}}.key'
    - '{{blog_domain}}.cer'
    
- name: copy nginx.conf
  template: 
    src: nginx/nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: copy blog.conf to nginx/conf.d/blog.conf
  template:
    src: nginx/blog.conf.j2
    dest: /etc/nginx/conf.d/blog.conf

- name: set blog location root
  file: 
    name: /usr/share/nginx/html/blog
    recurse: yes
    state: directory


