- name: modify systemd-journald 
  template: 
    src: journald/journald.conf.j2
    dest: /etc/systemd/journald.conf

- shell: 'systemctl restart systemd-journald'

- name: disable some services
  systemd: 
    name: "{{item}}"
    state: stopped
    enabled: no
  loop: 
    - fwupd
    - packagekit
    - unattended-upgrades
    - multipathd
    # 因为使用systemd.network，所以禁用NM
    - NetworkManager
    # 禁止无线网络管理
    - wpa_supplicant
    # 禁止移动设备的网络管理
    - ModemManager
    # 禁用和打印机相关的一切
    - cups-browsed
    - cups
    - cups.path
    - cups.socket
    # 禁用收集motd信息的定时任务
    - motd-news.timer
  failed_when: false

- name: enable swap because Memory is too small
  shell: |
    [ -f /swap ] || dd if=/dev/zero of=/swap bs=1M count=1024
    file /swap | grep swap >/dev/null || mkswap /swap && swapon /swap
    grep 'swap' /etc/fstab >/dev/null || echo "/swap swap swap defaults 0 0" >>/etc/fstab


