- name: install privoxy
  apt:
    name: privoxy
    state: present 

- name: copy privoxy config
  template: 
    src: privoxy/config.j2
    dest: /etc/privoxy/config

- name: start privoxy
  service: 
    name: privoxy
    state: restarted