- name: install trojan
  apt: 
    name: trojan
    state: present 
    
- name: create trojan ssl path
  file: 
    name: '{{trojan_ssl_path}}'
    state: directory

- name: copy trojan ssl to trojan ssl path
  template:
    src: 'ssl/{{item}}.j2'
    dest: '{{trojan_ssl_path}}/{{item}}'
  loop:
    - '{{trojan_domain}}.key'
    - '{{trojan_domain}}.cer'

- name: copy trojan ssl to nginx ssl path
  template:
    src: 'ssl/{{item}}.j2'
    dest: '{{nginx_ssl_path}}/{{item}}'
  loop:
    - '{{trojan_domain}}.key'
    - '{{trojan_domain}}.cer'

- name: copy trojan@.service
  template:
    src: trojan/trojan@.service.j2
    dest: /usr/lib/systemd/system/trojan@.service

- shell: 'systemctl daemon-reload'

- name: enable trojan@.service
  service: 
    name: "{{item}}"
    enabled: yes
  loop: 
    - trojan@server
    - trojan@client

- name: copy trojan config to /etc/trojan
  template: 
    src: 'trojan/{{item}}.j2'
    dest: '/etc/trojan/{{item}}'
  loop:
    - client.json
    - server.json

- name: copy trojan nginx conf
  template: 
    src: nginx/trojan.conf.j2
    dest: /etc/nginx/conf.d/trojan.conf




