- name: install ufw
  apt:
    name: ufw
    state: present 

- name: allow mine ip
  ufw:
    rule: allow
    from_ip: '39.186.0.0/16'

- name: allow some ports
  ufw: 
    rule: allow
    port: '{{item}}'
    proto: tcp
  loop: 
    - 80
    - 443
    - {{trojan_server_port}}
    - {{trojan_client_port}}

- name: enable ufw
  ufw: 
    state: enabled